upd h5vtk and h5bop; add test

diff --git a/poc/h5vtk b/poc/h5vtk
--- a/poc/h5vtk
+++ b/poc/h5vtk
@@ -1,25 +1,31 @@
 #!/bin/bash
 
 usg() {
-    echo 'h5vtk [dir] [h5part]
-converts h5part to a list of vtk files' >&2
+    echo 'usage h5vtk dirname h5part
+  converts h5part of vtk files' >&2
     exit
 }
 
-if test $# -ne 0 -a $1 = -h; then usg; fi
+msg() { printf "$@" >&2; }
+err() { msg 'h5vtk: '; msg "$@"; msg '\n'; exit 1; }
 
+if test $# -ne 0 -a "$1" = -h; then usg; fi
+
+if test $# -eq 0; then err 'not enough arguments'; fi
 d="$1"; shift
+
+if test $# -eq 0; then err 'not enough arguments'; fi
 s="$1"; shift
 
-if test ! -f "$s"; then usg; fi
-if test $# -ne 0 ; then usg; fi
+if test ! -f "$s"; then err 'fail to load %s' "$s"; fi
 
 t=/tmp/h5vtk.$$
 
 trap 'rm -rf $t' 0 1 2 3 15
 
-h5bop "$t" "$s"
-mkdir -p "$d"
+if ! h5bop "$t" "$s"; then err 'h5bop failed'; fi
+mkdir -p "$d" 2> /dev/null
+if test ! -d "$d"; then err 'cannot create directory %s' "$d"; fi
 
 (cd "$t"
  for b in *.bop
@@ -29,3 +35,8 @@ mkdir -p "$d"
  done)
 
 for v in $t/*.vtk; do mv $v "$d"; done
+
+# TEST: h5vtk
+# h5vtk d test_data/all.h5part
+# mv d/0000.vtk h.out.vtk
+#
